version: "3.7"
services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=uir
  #    volumes:
  #      - postgres-db:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8081:8080"
    restart: unless-stopped